MyWeb1.0/Models/ApplicationContext.cs
using Microsoft.EntityFrameworkCore;

namespace MyWeb1._0.Models
{
    public class ApplicationContext:DbContext
    {
        public DbSet<User> Users { get; set; } = null!;
        public DbSet<Game> Games { get; set; } = null!;
        public ApplicationContext(DbContextOptions<ApplicationContext> options):base(options)
        {
            Database.EnsureCreated();
        }
    }
}

MyWeb1.0/Models/ErrorViewModel.cs
namespace MyWeb1._0.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyWeb1.0/Models/Game.cs
using Microsoft.IdentityModel.Protocols.OpenIdConnect;

namespace MyWeb1._0.Models
{
    public class Game
    {
        private int id;
        private string? name;
        private string? description;
        private int price;
        private string? genre;
        private string? img;
        public int Id { get { return id; } set { id = value; } }

        public string? Name { get { return name; } set { name = value; } }

        public string? Description { get { return description; } set { description = value; } }

        public int Price { get { return price; } set { price = value; } }

        public string? Genre { get { return genre; } set { genre = value; } }

        public string? Img { get { return img; } set { img = value; } }

    }
}

MyWeb1.0/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace MyWeb1._0.Models
{
    public class User
    {
        public int Id { get; set; }

        [Display(Name="Введите имя: ")]
        [MinLength(2,ErrorMessage ="Минимальная длинна должна быть больше 2 символов")]
        [MaxLength(15, ErrorMessage = "Длинна не должна превышать 15 символов")]
        [Required(ErrorMessage ="Вам нужно ввести имя")]
        
        public string? Name { get; set; }

        [Display(Name = "Введите фамилию: ")]
        [MinLength(2, ErrorMessage = "Минимальная длинна должна быть больше 2 символов")]
        [MaxLength(15, ErrorMessage = "Длинна не должна превышать 15 символов")]
        [Required(ErrorMessage = "Вам нужно ввести фамилию")]
        public string? Surname { get; set; }

        [Display(Name = "Введите возраст: ")]
        [Range(1,110,ErrorMessage ="Недопустимый возраст")]
        [Required(ErrorMessage = "Вам нужно ввести возраст")]
        public int Age { get; set; }

        [Display(Name = "Введите почту: ")]
        [EmailAddress]
        [Required(ErrorMessage = "Вам нужно ввести почту")]
        public string? Email { get; set; }
    }
}

MyWeb1.0/Controllers/AddController.cs
using Microsoft.AspNetCore.Mvc;
using MyWeb1._0.Models;

namespace MyWeb1._0.Controllers
{
    public class AddController : Controller
    {
        ApplicationContext db;

        public AddController(ApplicationContext context)
        {
            db = context;
        }
        public IActionResult Index() => View();

        [HttpPost]
        public async Task<IActionResult> CreateGame(Game game)
        {
            if (ModelState.IsValid)
            {
                db.Games.Add(game);
                await db.SaveChangesAsync();
                return Redirect("/");
            }

            return View("Index");
        }
    }
}

MyWeb1.0/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyWeb1._0.Models;

namespace MyWeb1._0.Controllers
{
    public class HomeController : Controller
    {
        ApplicationContext db;
        public HomeController(ApplicationContext context)
        {
            db = context;
        }
        public IActionResult Index()
        {
            return View();
        }
       
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                User? user = await db.Users.FirstOrDefaultAsync(p => p.Id == id);
                if (user != null) return View(user);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(User user)
        {
            db.Users.Update(user);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

    }

}

MyWeb1.0/Controllers/InfoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyWeb1._0.Models;

namespace MyWeb1._0.Controllers
{
    public class InfoController : Controller
    {
        ApplicationContext db;
        public InfoController(ApplicationContext context)
        {
            db = context;
        }

        public async Task<IActionResult> Index()
        { 
            return View(await db.Users.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                User? user = await db.Users.FirstOrDefaultAsync(p => p.Id == id);
                if (user != null)
                {
                    db.Users.Remove(user);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }

    }
}

MyWeb1.0/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyWeb1._0.Controllers
{
    public class RegisterController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

    }
}

MyWeb1.0/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyWeb1._0.Models;
using Microsoft.AspNetCore.Authorization;

namespace MyWeb1._0.Controllers
{
    [Authorize]
    public class ShopController : Controller
    {
        ApplicationContext db;
        public ShopController(ApplicationContext context)
        {
            db = context;
        }
        public async Task<IActionResult> Index()
        {
            return View(await db.Games.ToListAsync());
        }
    }
}

MyWeb1.0/Views/Add/Index.cshtml
@model MyWeb1._0.Models.Game
@{
    ViewData["Title"] = "AddGames";
}

<header id="display-4">
    <h1 id="title-2">Добавление новой игры в магазин</h1>
</header>

<main id="display-5">
    <form asp-action="CreateGame" asp-controller="Add"  method="post"> 
    <label id="nameGame" asp-for="Name"></label>
    <input id="nameGame" asp-for="Name"/>
    <br/>
    <label id="surname-1" asp-for="Genre"></label>
    <input id="surname-2" asp-for="Genre"/>
    <br/>
    <label id="age-1" asp-for="Description"></label>
    <input id="age-2" asp-for="Description"/>
    <br/>
    <label id="email-1"asp-for="Price"></label>
    <input id="email-2"asp-for="Price"/>
    <br/>
    <label id="email-1"asp-for="Img"></label>
    <input id="email-2"asp-for="Img"/>
    <br/>

    <input id="button-1" type="submit" value="Добавить"/> 
    </form>
</main>

<footer id="display-6">

</footer>

MyWeb1.0/Views/Home/Edit.cshtml
@model MyWeb1._0.Models.User
@{
    ViewData["Title"] = "Redact user";
}

<h1>Редактирование пользователя</h1>

<main>
    <form asp-action="Edit" asp-controller="Home" asp-route-id="@Model.Id">
    <p>
        <label asp-for="Name">Имя</label><br />
        <input type="text" asp-for="Name" />
    </p>
    <p>
        <label asp-for="Surname">Фамилия</label><br />
        <input type="text" asp-for="Surname" />
    </p>
    <p>
        <label asp-for="Age">Возраст</label><br />
        <input type="number" asp-for="Age" />
    </p>
    <p>
        <label asp-for="Email">Почта</label><br />
        <input type="text" asp-for="Email" />
    </p>
    <p>
        <input type="submit" value="Сохранить" />
    </p>
    </form>
</main>

MyWeb1.0/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Главная страница";
}

<header id="display">
    <div id="title">Welcome to Game Online Shop!</div>
        <ul id="nav">
        <li><a href="/register">Регистрация</a></li>
        <li><a href="/info">Новые пользователи</a></li>
         <li><a href="/add">Добавить новые игры</a></li>
        <li><a href="/shop">Магазин</a></li>
        <li><a href="/">Контакты</a></li>
        <li><a href="/">О нас</a></li>
      </ul>
</header>

<main id="display-2">
<div id="menu"> 
      Lorem ipsum dolor sit amet, consectetur
      adipisicing elit, sed do eiusmod tempor incididunt ut
      labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex
      ea commodo consequat. Duis aute irure dolor in reprehenderit 
      in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
      Excepteur sint occaecat cupidatat non proident, sunt in culpa qui
      officia deserunt mollit anim id est laborum.
      Lorem ipsum dolor sit amet, consectetur
      adipisicing elit, sed do eiusmod tempor incididunt ut
      labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex
      ea commodo consequat. Duis aute irure dolor in reprehenderit 
      in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
      Excepteur sint occaecat cupidatat non proident, sunt in culpa qui
      officia deserunt mollit anim id est laborum.
       Lorem ipsum dolor sit amet, consectetur
      adipisicing elit, sed do eiusmod tempor incididunt ut
      labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex
      ea commodo consequat. Duis aute irure dolor in reprehenderit 
      in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
      Excepteur sint occaecat cupidatat non proident, sunt in culpa qui
      officia deserunt mollit anim id est laborum.
      Lorem ipsum dolor sit amet, consectetur
      adipisicing elit, sed do eiusmod tempor incididunt ut
      labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex
      ea commodo consequat. Duis aute irure dolor in reprehenderit 
      in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
      Excepteur sint occaecat cupidatat non proident, sunt in culpa qui
      officia deserunt mollit anim id est laborum.
  </div>
</main>

<footer id="display-3">
     <h1 id="dis-3">Copyright © gameshop.com, 2023. Все права защищены.<br/>
                    Контакты для связи: o.zelenskii@mail.ru
     </h1>
     
</footer>

MyWeb1.0/Views/Info/Index.cshtml
@model IEnumerable<MyWeb1._0.Models.User>

@{
    ViewData["Title"] = "InfoUser";
}

<h1>Информация о новых пользователях</h1>
<table class="table">
     <tr><th>Имя</th><th>Фамилия</th><th>Возраст</th><th>Почта</th></tr>
    @foreach (var item in Model)
    {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Surname</td>
                    <td>@item.Age</td>
                    <td>@item.Email</td>
                    <td>
                        <a asp-action="Edit" asp-controller="Home" asp-route-id="@item.Id">Изменить</a>
                    </td>
                    <td>
                           <form asp-controller="Info" asp-action="Delete" method="post"  asp-route-id="@item.Id">
                        <input type="submit" value="Удалить"/>
                    </form>
                    </td>
                </tr>
    }
</table>

<main class="button">
 <a href="/Home">Вернуться на главную</a>
</main>

MyWeb1.0/Views/Register/Index.cshtml
@model MyWeb1._0.Models.User
@{
    ViewData["Title"] = "Registration";
}

<header id="display-4">
    <h1 id="title-2">Регистрация нового пользователя</h1>
</header>

<main id="display-5">
    <form asp-action="CreateUser" asp-controller="Register"  method="post"> 
    <span id="validation" asp-validation-for="Name"></span><br/>
    <label id="name-1" asp-for="Name"></label>
    <input id="name-2" asp-for="Name"/>
    <br/>
    <span id="validation" asp-validation-for="Surname"></span><br/>
    <label id="surname-1" asp-for="Surname"></label>
    <input id="surname-2" asp-for="Surname"/>
    <br/>
    <span id="validation" asp-validation-for="Age"></span><br/>
    <label id="age-1" asp-for="Age"></label>
    <input id="age-2" asp-for="Age"/>
    <br/>
    <span id="validation" asp-validation-for="Email"></span><br/>
    <label id="email-1"asp-for="Email"></label>
    <input id="email-2"asp-for="Email"/>
    <br/>
    
    <input id="button-1" type="submit" value="Отправить"/> 
    </form>
</main>

<footer id="display-6">

</footer>

MyWeb1.0/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineGameShop</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" /> 
</head>
<body>
    <header>
       
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        
    </footer>
</body>
</html>

MyWeb1.0/Views/Shop/Index.cshtml
@model IEnumerable<MyWeb1._0.Models.Game>
@{
    ViewData["Title"] = "GameShop";
}

<header id="display">
    <div id="title">Welcome to Game Online Shop!</div>
</header>

<main id="display-2">
     <h1>Игры в магазине</h1>
     <div id="category"> 
     <table class="table">
     <tr><th>Название игры </th><th>Жанр</th><th>Описание</th><th>Цена</th><th>Изображение</th></tr>
            @foreach (var item in Model)
            {
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.Genre</td>
                        <td>@item.Description</td>
                        <td>@item.Price</td>
                        <td>@item.Img</td>
                    </tr>
            }
     </table>
     </div>
</main>

<footer id="display-3">
     <h1 id="dis-3">Copyright © gameshop.com, 2023. Все права защищены.<br/>
                    Контакты для связи: o.zelenskii@mail.ru
     </h1>
</footer>